config/routes.rb
Rails.application.routes.draw do
  get 'image/banner/:image', to: 'image#banner', as: 'image_banner'
  get 'image/:image', to: 'image#show', as: 'image'
  get 'home', to: 'home#index', as: 'home'
  get 'about', to: 'about#show', as: 'about'
  get 'privacy_policy', to: 'about#privacy_policy', as: 'privacy_policy'
  get 'contact_us', to: 'about#contact_us', as: 'contact_us'
  
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    registration: 'register'
  }, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :notifications, only: [:index]
  resources :image, only: [:destroy]
  resources :ratings, only: [:create]
  resources :comments, only: [:create, :destroy]
  resources :pins, only: [:create, :destroy]
  resources :products, only: [:show]
  resources :posts, only: [:show, :destroy]
  resources :tourisms
  resources :profiles, except: [:index, :destroy, :create] do
    get 'communities'
    get 'tourisms'
    get 'shops'
    get 'pins'
    get 'map'
    put 'update_password'
  end

  resources :communities, except: [:index] do 
    resources :posts, only: [:create, :destroy]
  end

  resources :orders, except: [:new, :edit] do 
    collection do 
      get 'mine'
    end
  end
  
  resources :shops, except: [:index] do
    resources :products
  end


  root 'home#index'
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#server_error', via: :all
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
  validates :message, presence: true
  validates :user, presence: true

  after_create :notify_commentable_users

  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :ratings, as: :rateable

  def notify_commentable_users
    notifications_params = self.commentable.comments.map{|c| {user: c.user, notifiable: self.commentable, from_user: self.user, category: 'commented'} unless c.user == self.user }.compact.uniq
    notifications_params << {user: self.commentable.user, notifiable: self.commentable, from_user: self.user, category: 'commented'} if self.commentable.user != self.user
    self.commentable.notifications.create(notifications_params.uniq)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    klass, id, message = params[:type].constantize, params[:type_id], params[:message]

    model = klass.find(id)
    @comment = model.comments.create(user: current_user, message: message)
    index = params[:type].downcase
    
    if @comment.errors.present?
      flash.now[:error] = @comment.errors.full_messages.first 

      render status: 500
    else
      html_to_public = render_to_string(partial: 'comment', locals: { comment: @comment, current_user: nil })
      html_to_owner = render_to_string(partial: 'comment', locals: { comment: @comment, current_user: current_user })
      WebsocketRails[:comments].trigger 'new', { raw: @comment, html: { owner: html_to_owner, public: html_to_public }, comments: model.comments.size, element: "comments-#{index}-#{model.id}"}
    end

    respond_to do |format|
      format.js
      format.html { return redirect_to(:back) }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    WebsocketRails[:comments].trigger 'destroy', { raw: @comment }
    
    respond_to do |format|
      format.js
      format.html { return redirect_to(:back) }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.comment.feedback data-comment=comment.id
  .col-md-12
    .box
      .box-header.with-border
        .user-avatar.pull-left
          - if comment.user.image_url?
            img src=comment.user.image_url
          - else
            span.glyphicon.glyphicon-user.font-size-40.mR10
        h3.box-title.pull-left.mT5
          = link_to profile_path(comment.user) do
            p.mB0 
              = comment.user.full_name
            small
              = timeago_tag(comment.created_at, :nojs => true, :limit => 10.days.ago)
        .pull-right
          - if current_user == comment.user
            = button_to comment_path(comment), method: :delete, remote: true, class: 'btn btn-sm btn-flat btn-default text-black text-center pB0 pT0', data: { disable_with: 'removing...'} do
              span remove
      .box-body
        p
          = raw comment.message

app/views/comments/_form.html.slim
= form_tag comments_path, role: 'form', remote: true, id: 'new_comment', authenticity_token: true do

    = hidden_field_tag(:type, model.class.name)
    = hidden_field_tag(:type_id, model.id)
    / message
    .form-group
      = text_area_tag(:message, nil, class: 'form-control wysi-editor', placeholder: 'Write comment...')
    .form-group
      = submit_tag 'Submit Comment', class: 'btn btn-block btn-success',  data: { disable_with: "Processing..." }

app/views/comments/_list.html.slim
.comments.feedbacks id='comments-#{model.class.name.downcase}-#{model.id}'
  .box.box-solid
    .box-header.bg-green
      h3.box-title Comments
      .box-tools.pull-right
        button.btn.btn-box-tool data-widget='collapse'
          span.ion.ion-minus
    .box-body
      .row
        .inner-comments
          
          - if model.comments.empty?
            p.text-center No comments yet.
          - else
            = render model.comments
    .box-footer
      = comment_form(model) if show_form

app/views/comments/create.js.erb
<% unless @comment.errors.blank? %>
  setTimeout(function() {
    $('.comments .box-footer').prepend("<%= escape_javascript(render 'shared/flash') %>")
  }, 100)
<% end %>

app/views/comments/destroy.js.erb
$('div[data-comment="<%= @comment.id %>"]').remove()