config/routes.rb
Rails.application.routes.draw do
  get 'image/banner/:image', to: 'image#banner', as: 'image_banner'
  get 'image/:image', to: 'image#show', as: 'image'
  get 'home', to: 'home#index', as: 'home'
  get 'about', to: 'about#show', as: 'about'
  get 'privacy_policy', to: 'about#privacy_policy', as: 'privacy_policy'
  get 'contact_us', to: 'about#contact_us', as: 'contact_us'
  
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    registration: 'register'
  }, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :notifications, only: [:index]
  resources :image, only: [:destroy]
  resources :ratings, only: [:create]
  resources :comments, only: [:create, :destroy]
  resources :pins, only: [:create, :destroy]
  resources :products, only: [:show]
  resources :posts, only: [:show, :destroy]
  resources :tourisms
  resources :profiles, except: [:index, :destroy, :create] do
    get 'communities'
    get 'tourisms'
    get 'shops'
    get 'pins'
    get 'map'
    put 'update_password'
  end

  resources :communities, except: [:index] do 
    resources :posts, only: [:create, :destroy]
  end

  resources :orders, except: [:new, :edit] do 
    collection do 
      get 'mine'
    end
  end
  
  resources :shops, except: [:index] do
    resources :products
  end


  root 'home#index'
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#server_error', via: :all
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  mount_uploader :banner_image, BannerImageUploader
  
  extend FriendlyId
  include FriendlyParamHelper
  include OwnerHelper
  include PaginationHelper
  include BannerImageHelper

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :category, presence: true
  validates :location, presence: true
  validates :mobile, 
    presence: true, 
    numericality: { only_integer: true, message: ' number is not a number' }, 
    length: { is: 11, message: 'Mobile number should be 11 digits' }
  validates :telephone, 
    allow_blank: true,
    numericality: { only_integer: true, message: ' number is not a number' }, 
    length: { is: 10, message: 'Telephone number should be 10 digits' }
  validates :banner_image, presence: true, on: [:create]
  validates :status, presence: true
  validates :user, presence: true
  
  belongs_to :user
  has_many :products, dependent: :destroy
  has_many :ratings, as: :rateable, dependent: :destroy
  has_many :pins, as: :pinnable, dependent: :destroy
  has_many :views, as: :viewable, dependent: :destroy
  
  CATEGORIES = %w(native travel delicacy vegetable fruit souvenier resort restaurant market wet_market)
  STATUSES = %w(open closed inactive)
  
  STATUSES.each do |status|
    define_method "#{status}?" do
      self.status == status
    end
  end

  def recent
    limit(8)
  end

  def contact_number
    return "#{mobile} / #{telephone}" unless mobile.blank? || telephone.blank?

    mobile.presence or telephone.presence
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  load_and_authorize_resource param_method: :sanitize_params

  def new
    @shop = Shop.new
  end

  def edit 
  end

  def show
    visit_resource! @shop
  end

  def create
    @shop.user = current_user

    if @shop.valid?
      @shop.save
      flash.now[:success] = "Successfully Created #{@shop.name}."
      return redirect_to @shop, turbolinks: true
    end

    flash.now[:error] = @shop.errors.full_messages.first
    render :new
  end

  def update

    if @shop.update_attributes(params.require(:shop).permit(shop_params))
      flash.now[:success] = "Sccuessfully updated #{@shop.name}."
      return redirect_to @shop, turbolinks: true
    end

    flash.now[:error] = @shop.errors.full_messages.first
    render :edit
  end

  def destroy
  end

  private
    def sanitize_params
      params.require(:shop).permit(shop_params)
    end

    def shop_params
      %w(name description category location mobile telephone banner_image status)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def active?(i)
    'active' if i == 0
  end

  def category_options_for_shop(shop)
    categories = Shop::CATEGORIES.map{|c| [c.gsub('_', ' ').humanize, c] }
    options_for_select categories, selected: shop.try(:category)
  end

  def status_options_for_shop(shop)
    statuses = Shop::STATUSES.map{|c| [c.gsub('_', ' ').humanize, c] }
    options_for_select statuses, selected: shop.try(:status)
  end

  def shop_recent_label(current_user, shop)
    "#{@shop.user.full_name}'s Shops" unless shop.owner?(current_user)
  end
end

app/views/shops/_form.html.slim
= form_for @shop, role: 'form' do |f|
  .box-body
    / Name
    .form-group
      label Name
      = f.text_field :name, class: 'form-control', placeholder: 'Name'
    / Description
    .form-group
      label Description
      = f.text_area :description, class: 'form-control wysi-editor', placeholder: 'Description'
    / Category
    .form-group
      label Category
      = f.select :category, category_options_for_shop(@shop), {}, class: 'form-control select-2', placeholder: 'Category'
    / Location
    .form-group
      label Location
      = f.select :location, location_options(@shop), {}, class: 'form-control select-2', placeholder: 'Location'
    / Contact Mobile Number
    .form-group
      label Contact Mobile Number
      = f.text_field :mobile, class: 'form-control', placeholder: 'Mobile Number'
    / Contact Telephone Number
    .form-group
      label Contact Telephone Number
      = f.text_field :telephone, class: 'form-control', placeholder: 'Telephone Number'
    / Banner Image
    .form-group
      label Banner Image (recommended banner size: 1024x500 pixel)
      = f.file_field :banner_image, class: 'form-control', placeholder: 'Banner Image', accept: 'image/png,image/gif,image/jpeg'
    / Status
    .form-group
      label Status
      = f.select :status, status_options_for_shop(@shop), {}, class: 'form-control select-2', placeholder: 'Status'
  .box-footer
    .row
      .col-md-6.mT5
        = link_to 'Cancel', :back || root_path, class: 'btn btn-default btn-block'
      .col-md-6.mT5
        = f.submit 'Save', class: 'btn btn-block btn-success',  data: { disable_with: "Processing..." }

app/views/shops/_resource_actions.html.slim
.resource-actions.links
  .btn-group
    - if @shop.owner?(current_user)
      = link_to edit_shop_path(@shop), class: 'btn btn-default btn-flat btn-sm' do 
        span.glyphicon.glyphicon-pencil.mR10
        span Edit
      = link_to new_shop_product_path(@shop), class: 'btn btn-default btn-flat btn-sm' do 
        span.glyphicon.glyphicon-briefcase.mR10
        span New product
    = link_to profile_path(@shop.user), class: 'btn btn-default btn-flat btn-sm', title: 'Shop Owner' do 
      span.glyphicon.glyphicon-user.mR10
      span 
        = @shop.user.full_name.humanize
  

app/views/shops/_shop.html.slim
li.shop id='shop-#{shop.id}'
  span.font-size-20.glyphicon.glyphicon-tent.bg-green
  .timeline-item
    span.label.label-success.pull-right
      = shop.category.downcase
    .time 
      = timeago_tag(shop.created_at, :nojs => true, :limit => 10.days.ago)
    .timeline-header
      = link_to shop.name.humanize, shop_path(shop), class: 'title primary-color'
    .timeline-body
      .timeline-image
        - if shop.banner_image?
          .previewer
            .preview style='background-image: url(#{shop.banner_image_url})'
        - else
          span.ion-image
      p.short-description
       = sanitize_text(shop.description)
    
    - if shop.owner?(current_user)
      .timeline-footer.with-border
        .clearfix
          .pull-right
            = link_to edit_shop_path(shop), class: 'btn btn-sm pT0 pB0 btn-default btn-flat' do
              span.ion-edit.mR10
              span edit

app/views/shops/_shop_list.html.slim
.box.box-success.box-solid
  .box-header
    h3.box-title
      = defined?(title) && title.nil? ? 'My Shops' : title
    .box-tools.pull-right
      button.btn.btn-box-tool data-widget='collapse'
        span.ion.ion-minus
  .box-body
    - if @shop.user.shops.empty?
      p.text-center No shop created yet.
    - else
      ul.products-list.product-list-in-box
        - @shop.user.shops[0, 10].each do |shop|
          = link_to shop_path(shop) do
            li.item
              .product-info
                .product-title
                  = shop.name
                .product-description
                  = shop.location.humanize 

app/views/shops/create.html.slim
h1 Shops#create
p Find me in app/views/shops/create.html.slim

app/views/shops/destroy.html.slim
h1 Shops#destroy
p Find me in app/views/shops/destroy.html.slim

app/views/shops/edit.html.slim
- content_for(:content_header) do 
  .row
    .col-md-12
      h3 
        span.glyphicon.glyphicon-tent.mR10
        span Edit Shop - #{@shop.name.humanize}

.row
  / form
  .col-md-8
    .slide-in
      .box.box-success.box-solid
        .box-header
          h3.box-title 
            span.glyphicon.glyphicon-pencil.mR10
            span Edit Shop
        = render 'form'
      / banner image
      - unless @shop.banner_image.blank?
        .box.box-solid.box-success.banner_image_preview
          .box-header
            h3.box-title
              span.glyphicon.glyphicon-picture.mR10
              span Banner Image
          .box-body
            .row
              .col-md-12
                .text-center
                  / img src=image_banner_path(@shop.banner_image_url, size: 600) 
                  = image_tag(@shop.banner_image_url)       

  / shops
  .col-md-4
    = render 'shop_list', title: nil

app/views/shops/new.html.slim
- content_for(:content_header) do 
  .row
    .col-md-12
      h3 
        span.ion.glyphicon.glyphicon-tent.mR10
        span Create New Shop

.row
  / form
  .col-md-8.col-md-offset-2
    .slide-in
      .box.box-success.box-solid
        .box-header
          h3.box-title 
            span.glyphicon.glyphicon-plus-round.mR10
            span New Shop
        = render 'form'

app/views/shops/show.html.slim
- content_for(:content_header) do 
  .row
    .col-md-10.col-md-offset-1
      .banner-header
        - unless @shop.banner_image.blank?
          .image style='background-image: url(#{@shop.banner_image_url})'
        .banner-title
          .pull-left
            h3
              = @shop.name.humanize
            p
              strong.glyphicon.glyphicon-map-marker.mR10
              span = @shop.location.humanize
            p
              strong.glyphicon.glyphicon-phone.mR10
              span = @shop.contact_number.humanize
          / view count
          .pull-right.links.mR10
            = link_to profile_path(@shop.user), class: 'thumbnail', data: { placement: 'left' }, title: "Shop Owner: #{@shop.user.full_name.humanize}" do
              - if @shop.user.image_url?
                = image_tag(@shop.user.image_url)
              - else
                span.ion-person.font-size-30
            = render 'shared/view_count_button'

        .banner-category
          p.label.label-danger
            = "Shop: #{@shop.category.humanize}"
        .mL10
          = button_raters(@shop, current_user, { comment: true })
.row
  .col-md-10.col-md-offset-1.mT-15
    .slide-in
      / details
      .details
        .box.box-solid
          .box-header
            h3.box-title
              .mT10
                span.glyphicon.glyphicon-info-sign.mR10
                span.header-label Description
              = render 'resource_actions'
          .box-body
            p
             = raw @shop.description
      / products
      .products
        h4.bg-green.p10 Available Products
        - if @shop.products.empty?
          p.text-center.mT20 No products available.
        - else
          .row
            - @shop.products.each do |product|
              .col-md-4
                .item
                  = link_to shop_product_path(@shop, product) do 
                    .image-holder
                      / image
                      .item-image
                        - if product.images.first
                          .inner-image style='background-image: url(#{product.images.first.medium_url})'
                        - else
                          p.text-center No Image
                    / name
                    .item-content
                      h4
                        = product.name
                      / price
                      p
                        strong Price: 
                        span
                          = currency_format product.price
                      / created
                    .timeago 
                      p Posted #{timeago_tag(product.created_at, :nojs => true, :limit => 10.days.ago)}
  

app/views/shops/update.html.slim
h1 Shops#update
p Find me in app/views/shops/update.html.slim