config/routes.rb
Rails.application.routes.draw do
  get 'image/banner/:image', to: 'image#banner', as: 'image_banner'
  get 'image/:image', to: 'image#show', as: 'image'
  get 'home', to: 'home#index', as: 'home'
  get 'about', to: 'about#show', as: 'about'
  get 'privacy_policy', to: 'about#privacy_policy', as: 'privacy_policy'
  get 'contact_us', to: 'about#contact_us', as: 'contact_us'
  
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    registration: 'register'
  }, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :notifications, only: [:index]
  resources :image, only: [:destroy]
  resources :ratings, only: [:create]
  resources :comments, only: [:create, :destroy]
  resources :pins, only: [:create, :destroy]
  resources :products, only: [:show]
  resources :posts, only: [:show, :destroy]
  resources :tourisms
  resources :profiles, except: [:index, :destroy, :create] do
    get 'communities'
    get 'tourisms'
    get 'shops'
    get 'pins'
    get 'map'
    put 'update_password'
  end

  resources :communities, except: [:index] do 
    resources :posts, only: [:create, :destroy]
  end

  resources :orders, except: [:new, :edit] do 
    collection do 
      get 'mine'
    end
  end
  
  resources :shops, except: [:index] do
    resources :products
  end


  root 'home#index'
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#server_error', via: :all
end

app/views/shared/_button_raters.html.slim
.button-raters.mB5.mT5
  .btn-group role='group'
    - unless disabled[:rate]
      / thumbs up
      .btn-group.positive-rate role='group'
        = button_to ratings_path({ category: 'positive', type_id: model.id, type: model.class.name }), form_class: 'rate-button', method: :post, remote: true, class: "btn btn-sm btn-default #{rated!(model, 'positive', current_user)}", id: "#{model.class.name.downcase}-rate-positive-#{model.id}" do
          span.glyphicon.glyphicon-thumbs-up
          span.inner.mL10
            = ratings(model.ratings, 'positive')
      / thumbs down
      .btn-group.negative-rate role='group'
        = button_to ratings_path({ category: 'negative', type_id: model.id, type: model.class.name }), form_class: 'rate-button', method: :post, remote: true, class: "btn btn-sm btn-default #{rated!(model, 'negative', current_user)}", id: "#{model.class.name.downcase}-rate-negative-#{model.id}" do
          span.glyphicon.glyphicon-thumbs-down
          span.inner.mL10
            = ratings(model.ratings, 'negative')
    - unless disabled[:pin]
      / pin
      .btn-group.pin role='group'
        = button_to pins_path({ type_id: model.id, type: model.class.name }), form_class: 'pin-button', method: :post, remote: true, class: "btn btn-sm btn-default #{pinned!(model, current_user)}", id: "#{model.class.name.downcase}-pin-#{model.id}" do
          span.glyphicon.glyphicon-pushpin
          span.inner.mL10 
            = model.pins.size
    / comments
    - unless disabled[:comment]
      .btn-group.comment-count role='group'
        = button_tag class: 'btn btn-sm btn-default', disabled: true, id: "comments-#{model.class.name.downcase}-#{model.id}-count" do
          span.glyphicon.glyphicon-comment
          span.inner.mL10 
            = model.comments.size
          

app/views/shared/_flash.html.slim
- flash.delete(:timedout).each do |k, v|
  .alert.alert-dismissible class="alert-#{k}" role='alert'
    button.close type='button' data-dismiss='alert' aria-label='Close' 
      span aria-hidden='true' &times;
    = v

app/views/shared/_footer.html.slim
footer.footer.mT60
  p.text-center
    | &copy; 2015 #{'#{CodeFreeze}'} Lab. All rights reserved
  p.text-center
  	= link_to 'Home |', home_path
    = link_to 'About Us |', about_path
    = link_to 'Privacy Policy |', privacy_policy_path
    = link_to 'Contact Us', contact_us_path

app/views/shared/_header.html.slim
header.main-header
  / logo
  = link_to root_path, class: 'logo' do
    strong Kabuhayan Portal
  nav.navbar.navbar-static-top role='navigation'
    a.sidebar-toggle data-toggle='offcanvas' href=profile_path(current_user) role='button'
      span.glyphicon.glyphicon-align-justify
      span.sr-only Toggle Navigation
    
    / left
    .navbar-custom-menu.pull-left
      ul.nav.navbar-nav
        li
          = link_to root_path, title: 'Home' do 
            span.glyphicon.glyphicon-home.mR5
            span.header-label Home
        li
          = link_to tourisms_path, title: 'Tourisms' do
            span.glyphicon.glyphicon-tree-conifer.mR5
            span.header-label Tourism
    / right
    .navbar-custom-menu
      ul.nav.navbar-nav
        - if current_user
          / notifications
          = render 'shared/notifications'

          li.dropdown.user.user-menu
            = link_to profile_path(current_user) do
              div
                - if current_user.image_url?
                  = image_tag(current_user.image_url, class: 'user-image mR5' )
                - else
                  span.glyphicon.glyphicon-user.font-size-20.mR5
                span.header-label = current_user['full_name']
          li
            = link_to destroy_user_session_path, title: 'Sign out' do 
              span.glyphicon.glyphicon-log-out.font-size-18
        

app/views/shared/_load_more_button.html.slim
/ alert
.alert-notification.text-center
- unless resources.blank?
  - if resources.next_page
    .text-center.clearfix
      noscript
        .alert.alert-danger
          p
            strong Ops your javascript is disabled, you have to use the next page button instead of the load more button
        = link_to resources_url, class: 'btn btn-default text-center mB30' do 
          span NEXT PAGE
          span.ion-arrow-right-a.mL10
      / load more
      = button_to resources_url, method: :get, remote: true, class: 'btn btn-md btn-default text-center', data: { loading_text: 'Loading...'}, id: 'load_more' do
         span LOAD MORE

app/views/shared/_loader.html.slim
.loader
  .inner-loader
    p.spinner.ion-android-arrow-forward.rotate
    p Loading...

app/views/shared/_notifications.html.slim
li.dropdown.notifications-menu
  = link_to notifications_path, class: 'dropdown-toggle', data: { toggle: 'dropdown' }, aria_expanded: 'true' do 
    span.glyphicon.glyphicon-globe.font-size-20
    span.label.label-danger.count.font-size-12
      - if current_user.notifications.size > 0
        = current_user.notifications.size
  ul.dropdown-menu
    li.header Notifications
    li.slimScrollDiv.notification-holder
      ul.menu
        = render current_user.notifications
    li.footer
    	= link_to 'View All', notifications_path

app/views/shared/_remove_button.html.slim
- if resource.present? && resource.user == current_user
  = button_to resources_url, method: :delete, remote: true, class: 'btn btn-md btn-danger text-center' do
    span.ion-trash-a.mR10
    span remove

app/views/shared/_search_form.html.slim
= form_tag search_path, method: :get, id: 'search_form', enforce_utf8: false do
	- if location
		.mB10.col-md-3.pull-left
			= select_tag :location, search_location_options(params), class: 'form-control select-2', placeholder: 'Select Location'
	.input-group
	  = text_field_tag :keyword, params[:keyword], class: 'form-control', placeholder: search_placeholder
	  span.input-group-btn
	    = button_tag name: '', data: { disable_with: "Searching..." }, class: 'btn btn-success' do
	      span.ion-search

app/views/shared/_sidebar.html.slim
aside.main-sidebar
  section.sidebar
    ul.sidebar-menu
      li.header Personal
      / profile
      li.treeview
        = link_to profile_path(current_user)
          span.glyphicon.glyphicon-user
          span My Profile
      / pins
      li.treeview
        = link_to profile_pins_path(current_user)
          span.glyphicon.glyphicon-pushpin
          span My Pins
      / shops
      li.treeview
        = link_to '#'
          span.glyphicon.glyphicon-tent
          span My Shops
          i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          - unless current_user.shops.empty?
            - current_user.shops[0, 10].each do |shop|
              li
                = link_to shop_path(shop), class: 'ellipsis', title: shop.name do
                  span.ion.ion-arrow-right-c
                  span 
                    = shop.name

          li
            = link_to new_shop_path do 
              span.ion.ion-android-add-circle
              span Create new shop
          li
            = link_to profile_shops_path(current_user) do 
              span.ion.ion-ios-list
              span View all

      / tourisms
      li.treeview
        = link_to '#'
          span.glyphicon.glyphicon-tree-conifer
          span My Tourism
          i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          - unless current_user.tourisms.empty?
            - current_user.tourisms[0, 10].each do |tourism|
              li
                = link_to tourism_path(tourism), class: 'ellipsis', title: tourism.name do
                  span.ion.ion-arrow-right-c
                  span 
                    = tourism.name

          li
            = link_to new_tourism_path do 
              span.ion.ion-android-add-circle
              span Contribute to Tourism
          li
            = link_to profile_path(current_user) do 
              span.ion.ion-ios-list
              span View all

          li
            = link_to profile_map_path(current_user) do 
              span.ion.ion-ios-list
              span View all in the Map

      / communities
      li.treeview
        = link_to '#'
          span.glyphicon.glyphicon-blackboard
          span My Communities
          i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          - unless current_user.communities.empty?
            - current_user.communities[0, 10].each do |community|
              li
                = link_to community_path(community), class: 'ellipsis', title: community.name do
                  span.ion.ion-arrow-right-c
                  span 
                    = community.name

          li
            = link_to new_community_path do 
              span.ion.ion-android-add-circle
              span Create new Community
          li
            = link_to profile_communities_path(current_user) do 
              span.ion.ion-ios-list
              span View all

      / orders
      li.treeview
        = link_to '#'
          span.ion.ion-bag
          span Orders
          i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          li
            = link_to mine_orders_path do 
              span.ion.ion-ios-list
              span My Orders
          li
            = link_to orders_path do 
              span.ion.ion-ios-list
              span Buyers Orders

app/views/shared/_view_count_button.html.slim
- if @views.present?
  button.btn.btn-default.btn-sm.mL5.mR5.btn-flat.btn-view
    span
      = pluralize(@views.size, 'view')