config/routes.rb
Rails.application.routes.draw do
  get 'image/banner/:image', to: 'image#banner', as: 'image_banner'
  get 'image/:image', to: 'image#show', as: 'image'
  get 'home', to: 'home#index', as: 'home'
  get 'about', to: 'about#show', as: 'about'
  get 'privacy_policy', to: 'about#privacy_policy', as: 'privacy_policy'
  get 'contact_us', to: 'about#contact_us', as: 'contact_us'
  
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    registration: 'register'
  }, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :notifications, only: [:index]
  resources :image, only: [:destroy]
  resources :ratings, only: [:create]
  resources :comments, only: [:create, :destroy]
  resources :pins, only: [:create, :destroy]
  resources :products, only: [:show]
  resources :posts, only: [:show, :destroy]
  resources :tourisms
  resources :profiles, except: [:index, :destroy, :create] do
    get 'communities'
    get 'tourisms'
    get 'shops'
    get 'pins'
    get 'map'
    put 'update_password'
  end

  resources :communities, except: [:index] do 
    resources :posts, only: [:create, :destroy]
  end

  resources :orders, except: [:new, :edit] do 
    collection do 
      get 'mine'
    end
  end
  
  resources :shops, except: [:index] do
    resources :products
  end


  root 'home#index'
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#server_error', via: :all
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  include FriendlyParamHelper
  include PaginationHelper
  include ImagesValidatorHelper
  include OwnerHelper
  
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :category, presence: true
  validates :location, presence: true
  validates :images, presence: true, on: [:create]
  validates :price, presence: true, numericality: true
  validates :status, presence: true
  validates :shop, presence: true
  
  belongs_to :shop
  has_many :images, as: :imageable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :ratings, as: :rateable, dependent: :destroy
  has_many :views, as: :viewable, dependent: :destroy
  has_many :pins, as: :pinnable, dependent: :destroy
  has_many :orders
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_one :user, :through => :shop
  
  CATEGORIES = %w(food beverage vegetable fruits souvenier delicacy accomodation travel other seafood meat)
  STATUSES = %w(available sold inactive)

  STATUSES.each do |status|
    define_method "#{status}?" do
      self.status == status
    end
  end
  
  def self.search_all(page, keyword = nil, location = nil)
    includes(:comments, :ratings, :pins, :images, :shop, :user)
    .where(status: :available)
    .where('(products.name LIKE ? OR products.description LIKE ?) AND products.location LIKE ?', "%#{keyword}%", "%#{keyword}%", "%#{location}%")
    .paginate(page: page)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :find_shop, only: [:new, :create, :edit, :show, :update, :destroy]
  before_filter :find_product, only: [:edit, :show, :update, :destroy]
  load_and_authorize_resource param_method: :sanitize_params, except: [:new, :create]
  
  def index
  end

  def show
    notify_seen! @product
    visit_resource! @product
    @comment = Comment.new
  end

  def new
    return render_404 unless @shop.owner?(current_user)
    @product = Product.new
  end

  def edit
  end

  def create
    return render_404 unless @shop.owner?(current_user)
    @product = @shop.products.new(params.require(:product).permit(product_params))
    @product.images.new(params[:product][:images].map{|i| {file_name: i} }) unless params[:product][:images].blank?
    
    if @product.valid?
      @product.save
      flash.now[:success] = "Successfully Added new #{@product.name}."
      return redirect_to [@shop, @product], turbolinks: true
    end

    flash[:error] = @product.errors.full_messages.first
    render :new
  end

  def update
    @product.images.new(params[:product][:images].map{|i| {file_name: i} }) unless params[:product][:images].blank?
    
    if @product.update_attributes(params.require(:product).permit(product_params))
      flash.now[:success] = "Successfully updated #{@product.name}."
      return redirect_to [@shop, @product], turbolinks: true
    end

    flash.now[:error] = @product.errors.full_messages.first
    render :edit
  end

  def destroy
  end

  private
    def find_shop
      @shop = Shop.includes(:products).find(params[:shop_id]) if params[:shop_id]
    end

    def find_product
      @product = Product.find(params[:id])
    end

    def sanitize_params
      params.require(:product).permit(product_params)
    end

    def product_params
      %w(name description category price location images status)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def category_options_for_product(product)
    categories = Product::CATEGORIES.map{|c| [c.gsub('_', ' ').humanize, c] }
    options_for_select categories, selected: product.try(:category)
  end

  def status_options_for_product(product)
    statuses = Product::STATUSES.map{|c| [c.gsub('_', ' ').humanize, c] }
    options_for_select statuses, selected: product.try(:status)
  end

  def location_options_for_product(product)
    options_for_select locations, selected: product.try(:location)
  end

  def currency_format(number)
    raw "&#8369;#{number_to_currency(number, unit: '')}"
  end

  def request_sent_to_buy?(product)
    current_user.orders.select{|o| o.product == product && o.status == 'request_sent'}.first
  end

  def order_in_processed?(product)
    not_allowed_status = %w(cancelled rejected delivery_received)
    current_user.orders.select{|o| o.product == product && !not_allowed_status.include?(o.status) }.first
  end
end

app/views/products/_details.html.slim
ul.list-group
  li.list-group-item.bg-green
    p.title 
        span.pull-right
          = render 'shared/view_count_button'
        span Details
  li.list-group-item
    p
      strong Shop:
      strong.mL10 
        = link_to @product.shop.name.humanize, shop_path(@product.shop), class: 'primary-color'
  li.list-group-item
    p
      strong Shop Owner:
      span.mL10
        = link_to profile_path(@product.user) do
          = @product.user.full_name
  li.list-group-item
    p
      strong Price:
      span.mL10
        = currency_format(@product.price)
  li.list-group-item
    p
      strong Category:
      span.mL10
        = @product.category
  li.list-group-item
    p
      strong Status:
      span.mL10
        = @product.status.humanize
  li.list-group-item
    p
      strong Location:
      span.mL10
        = @product.location
  li.list-group-item
    p
      strong Contact:
      span.mL10 
        = @product.shop.contact_number
  li.list-group-item
    p 
      strong Created:
      span.mL10
        = timeago_tag(@product.created_at, :nojs => true, :limit => 10.days.ago)
  li.list-group-item
    p 
      strong Last Updated:
      span.mL10
        = timeago_tag(@product.updated_at, :nojs => true, :limit => 10.days.ago)

app/views/products/_form.html.slim
= form_for [@shop, @product], role: 'form' do |f|
  .box-body
    / Name
    .form-group
      label Name
      = f.text_field :name, class: 'form-control', placeholder: 'Name'
    / Description
    .form-group
      label Description
      = f.text_area :description, class: 'form-control wysi-editor', placeholder: 'Description'
    / Category
    .form-group
      label Category
      = f.select :category, category_options_for_product(@product), {}, class: 'form-control select-2', placeholder: 'Category'
    / Images
    .form-group
      label Images
      = f.file_field :images, class: 'form-control', placeholder: 'Images', accept: 'image/png,image/gif,image/jpeg', multiple: true
    / Price 
    .form-group
      label Price (Philippine Peso)
      = f.text_field :price, class: 'form-control', placeholder: 'Price'
    / Location
    .form-group
      label Location
      = f.select :location, location_options(@product), {}, class: 'form-control select-2', placeholder: 'Location'
    / Status
    .form-group
      label Status
      = f.select :status, status_options_for_product(@product), {}, class: 'form-control select-2', placeholder: 'Status'
  .box-footer
    .row
      .col-md-6.mT5
        = link_to 'Cancel', :back || root_path, class: 'btn btn-default btn-block'
      .col-md-6.mT5
        = f.submit 'Save', class: 'btn btn-block btn-success', data: { disable_with: "Processing..." }

app/views/products/_images.html.slim
- unless product.images.blank?
  .carousel.slide.product_images_slide id="product_images_slide-#{product.id}" data-ride='carousel' data-keyboard=true
    / indicators
    ol.carousel-indicators
      - product.images.each_with_index do |p, i|
        li data-target="#product_images_slide-#{product.id}" data-slide-to=i
    / images
    .carousel-inner
        - product.images.each_with_index do |p, i|
          .item class=active?(i)
            / img.col-md-12 src=image_path(p.image_url)
            = image_tag(p.image_url, class: 'col-md-12')
    / control
    = link_to "#product_images_slide-#{product.id}", class: 'left carousel-control', data: { slide: 'prev' } do
      span.fa.ion-chevron-left
    = link_to "#product_images_slide-#{product.id}", class: 'right carousel-control', data: { slide: 'next' } do
      span.fa.ion-chevron-right

app/views/products/_related_products.html.slim
- unless @shop.blank?
  .box.box-success.box-solid
    .box-header
      h3.box-title Related Products
      .box-tools.pull-right
        button.btn.btn-box-tool data-widget='collapse'
          span.ion.ion-minus
    .box-body
      - if (@shop.products - [@product]).empty?
        p.text-center No related products found.
      - else
         ul.products-list.product-list-in-box
          - (@shop.products - [@product])[0, 10].each do |product|
            = link_to shop_product_path(product.shop, product) do
              li.item
                .product-info
                  .product-title
                    = product.name.humanize
                  .product-description
                    = product.location 

app/views/products/_resource_actions.html.slim
.resource-actions
  - if @product.owner?(current_user)
    = link_to edit_shop_product_path(@product.shop, @product), class: 'btn btn-default btn-flat' do 
      span.glyphicon.glyphicon-pencil.mR10
      span.header-label Edit
    = link_to new_shop_product_path(@product.shop), class: 'btn btn-default btn-flat' do 
      span.glyphicon.glyphicon-plus.mR10
      span.header-label Add new to #{@product.shop.name.humanize}
  - else
    - if (order = request_sent_to_buy?(@product)).present?
      = button_to order_path(order), method: :delete, remote: true, class: 'btn btn-danger btn-flat' do
        span.ion-android-cart.mR10
        span.header-label Cancel buy request
    - elsif (order = order_in_processed?(@product)).present?
      = link_to order_path(order), class: 'btn btn-default btn-flat' do
        span.ion-android-cart.mR10
        span 
          = order.status.gsub('_', ' ')
    - else
      = button_to orders_path(product: @product), method: :post, remote: true, class: 'btn btn-success btn-flat' do
        span.ion-android-cart.mR10
        span.header-label Send buy request

app/views/products/edit.html.slim
- content_for(:content_header) do 
  .row
    .col-md-12
      h3 
        span.glyphicon.glyphicon-tags.mR10
        span Product - #{@product.name}

.row
  / form
  .col-md-8
    .slide-in
      .box.box-success.box-solid
        .box-header
          h3.box-title 
            span.glyphicon.glyphicon-pencil.mR10
            span Edit Product
        = render 'form'
      / images
      - unless @product.images.blank?
        .box.box-solid.box-success
          .box-header
            h3.box-title
              span.glyphicon.glyphicon-picture.mR10
              span Images Uploaded
          .box-body
            .flash-message
            .row
              - @product.images.each do |image|
                - if image.id?
                  .col-xs-4 id="product-thumb-#{image.id}"
                    .edit-image
                      .actions
                        = button_to image_path(image), method: :delete, remote: true, data: { disable_with: '...' } do 
                          span.ion.ion-android-cancel
                      = image_tag(image.medium_url)

  / shops
  .col-md-4
    = link_to shop_path(@product.shop), class: 'btn btn-success btn-block mB10' do 
      span.glyphicon.glyphicon-tent.mR10
      span Go to #{@product.shop.name.humanize}
    = render 'related_products'

app/views/products/new.html.slim
- content_for(:content_header) do 
  .row
    .col-md-12
      h3 
        span.glyphicon.glyphicon-tags.mR10
        span Add new product to #{@shop.name} shop

.row
  / form
  .col-md-8
    .slide-in
      .box.box-success.box-solid
        .box-header
          h3.box-title 
            span.glyphicon.glyphicon-plus-round.mR10
            span New product
        = render 'form'

  / related products
  .col-md-4
    = link_to shop_path(@shop), class: 'btn btn-success btn-block mB10' do 
      span.glyphicon.glyphicon-tent.mR10
      span Go to #{@shop.name.humanize}
    = render 'related_products'

app/views/products/show.html.slim
- content_for(:content_header) do 
  .row
    .col-md-12
      h3 
        span.glyphicon.glyphicon-tags.mR10
        span
          = @product.name.humanize
.row
  .col-md-8
    .slide-in
      / details
      .details
        .resource-images
          = render 'resource_actions'
          = render partial: 'images', locals: { product: @product }
        .box.box-solid
          .box-header
            h3.box-title 
              span.glyphicon.glyphicon-info-sign.mR10
              span Description
          .box-body
            p
             = raw @product.description
             
          .box-footer
            = button_raters(@product, current_user)

      / comments
      = comments(@product)
  / details
  .col-md-4
    = render 'details'
    = render 'related_products'